samsung-ipc/utils: reorder includes
This reorders includes alphabetically and groups them together:
- C standard library includes of depth 1 are grouped together
- "System" libraries of depth > 1 age grouped together
- The (lib)samsung-ipc include(s) is/are grouped together

We also need to keep the inclusion of sys/socket.h before linux/netlink.h
in order to prevent the following compilation error on Replicant 4.2:
    bionic/libc/kernel/common/linux/netlink.h:52:2: error: unknown type
    name 'sa_family_t'

While Replicant 4.2 is not really maintained anymore, it is still being
used for testing libsamsung-ipc on devices that are not supported anymore
by more recent Replicant versions, so we need to keep libsamsung-ipc and
libsamsung-ril working on it.

Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>