Fix vapi errors due to ipc_sms_send_msg and ipc_sms_deliv_report_msg renames.
Without that fix we have:
  smshandler.c:111:34: error: field 'ackmsg' has incomplete type
  smshandler.c:113:34: error: field '_tmp4_' has incomplete type

Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@no-log.org>