include: samsung-ipc.h: fix missing off_t definition
Including samsung-ipc.h in a file without other includes results
in a compilation error:
    .../include/samsung-ipc.h:161:1: error: unknown type name ‘off_t’
       161 | off_t file_data_size(struct ipc_client *client, [...]
           | ^~~~~

Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>