Fix vapi errors due to ipc_net_regist rename.
Without that fix we have many errors such as this one:
  mediators_network.c: In function 'samsung_network_get_status_real_run_co':
  mediators_network.c:1473:21: error: dereferencing pointer to incomplete type

Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@no-log.org>