tools: nv_data-imei: fix unused-label
Without that fix, when building libsamsung-ipc under GNU/Linux
with the "-Werror -W -Wall -Wunused -Wunused-function" CFLAGS,
GCC and the autotools build system, we have:
    nv_data-imei.c: In function ‘bruteforce_imei_offset’:
    nv_data-imei.c:695:1: error: label ‘complete’ defined
    but not used [-Werror=unused-label]
     complete:
     ^~~~~~~~

Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
Reviewed-by: Joonas Kylmälä <joonas.kylmala@iki.fi>