tools: ipc-modem: switch to Linux code style
This contains no functional changes.

checkpatch.pl still produces warning on tools/ipc-modem.c
but there were good reasons to ignore them:
- Since there is no documentation for the samsung-ipc
  protocol, beside the libsamsung-ipc source code, the
  code that was commented out or between #if 0 #endif
  has been preserved as it could be relevant to the
  understanding of the protocol.

  It will be kept until we understand why the code has been
  commented. In that case we either need to remove it completely
  or to replace it by a comment explaining why not having that
  code was necessary.
- checkpatch also emits many warnings for "quoted string
  split across lines". The issue here is that we have
  conflicting rules in the code style.
  - In one hand there is a limit of 80 characters per line.
  - On the other hand, user-visible strings should not
    be broken because "that breaks the ability to grep
    for them"[1].

  So the strings were split in a way that limit the
  probability of not finding them in grep.

The assignment of the global declaration to 0 also
triggered a checkpatch.pl error:
    ERROR: do not initialise globals to 0

So they were fixed as the fix shouldn't induce any
functional change: In the the C18 standard draft[2] in the
Semantics section of the Initialization section (6.7.9) we
have:
    If an object that has static or thread storage
    duration is not initialized explicitly, then:
    [...]
    - if it has arithmetic type, it is initialized to
    (positive or unsigned) zero;

References:
-----------
[1]https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/coding-style.rst?h=v5.6#n81
[2]The standard doesn't seem to be available for free, but the draft
   can be downloaded from the following URL:
   https://web.archive.org/web/20181230041359if_/http://www.open-std.org/jtc1/sc22/wg14/www/abq/c17_updated_proposed_fdis.pdf

Signed-off-by: Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
Reviewed-by: Joonas Kylmälä <joonas.kylmala@iki.fi>